
FROM python:3.9-slim


WORKDIR /app


COPY requirements.txt /app


RUN pip install --no-cache-dir -r requirements.txt


COPY . /app

# # Command to run when the container starts
# CMD [ "python", "ml_model.py" ]
